### ISSUE TITLE
What exact version of Python2 does this require?

### ISSUE THREAD

**Issue by RyanNgCT** [mspreitz/ADEL#2]
@mspreitz @svenschmitt Question up top. Trying to get it running but seems like its missing dependencies (python 2.7.18 doesn't seem to have the dependency it requires -- latest version of python 2.x on python.org as of writing)

Version of evidence to be processed: [Android 9, Google Pixel 3](https://digitalcorpora.org/corpora/cell-phones)

![image](https://user-images.githubusercontent.com/48358569/118786400-5b4ff680-b8c4-11eb-8507-7051caddccae.png)

Thanks!

**Comment by SchnWalter** [comment]
What happens if you type `adb --version` in the same console? I think that you don't have the SDK `platform-tools` directory in your global PATH.

**Comment by RyanNgCT** [comment]
So I'm guessing I have to add it to path as well @SchnWalter?

![Screenshot 2021-05-19 215009](https://user-images.githubusercontent.com/48358569/118824210-3e2f1e00-b8ec-11eb-9ddc-5719988e17c9.png)

**Comment by SchnWalter** [comment]
I haven't used this package, but by the looks of it, it's probably not made to work with the ADB package from PIP (which is a lot newer), you should probably download the official Android SDK platform tools and make sure that they are setup properly.

**Comment by mspreitz** [comment]
the code of ADEL is quite old/outdated and thus you really need to install the Android SDK (adb via PIP is not supported)
